name: PDM Lock and Add Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pdm_commands:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install PDM using official PDM action
      - name: Install PDM
        uses: pdm-project/setup-pdm@v4.1
        with:
            python-version: ${{ matrix.python-version }}

      # Run the PDM lock commands for different platforms
      - name: Run PDM lock for multiple platforms
        run: |
          pdm lock --platform linux \
          && pdm lock --platform windows --append \
          && pdm lock --platform macos_arm64 --append \
          && pdm lock --platform macos_x86_64 --append

      # Output the lock file
      - name: Output pdm.lock
        run: cat pdm.lock

      # Add tqdm package
      - name: Add tqdm package
        run: pdm add tqdm

      # Output the updated lock file
      - name: Output updated pdm.lock
        run: cat pdm.lock
